### ISSUE TITLE
Gameplay more smooth suggestion

### ISSUE THREAD

**Issue by Oliverlizard** [Nexyl-Roblox/Issues#17]
**Is your feature request related to a problem? Please describe.**
No, this feature is supposed to make gameplay smoother and nicer. The original is kinda sluggish and makes it hard to respond in fast paced situations

**Describe the solution you'd like**
Range circle round-up should be removed 

**Describe alternatives you've considered**
make it similar to TDX or TDS, it makes the gameplay feel much faster. And I'm pretty sure other players would prefer it

**Additional context**
PD example: https://cdn.discordapp.com/attachments/1145220489615261798/1183744989822451813/Roblox_2023-12-11_07-06-40.mp4?ex=6589736e&is=6576fe6e&hm=422d33a3867510829783d6b0ea6cc914816126fc7d7846ca3ff31f445a7b4e0b&

TDX example: https://cdn.discordapp.com/attachments/1145220489615261798/1183745526160707694/Roblox_2023-12-11_07-17-10.mp4?ex=658973ee&is=6576feee&hm=55049d875a23a0a512fb49e56b8df21703238e9eeb22a345a6d6619104760b0b&

This feature should also apply to the outline effect since that's also cool
https://cdn.discordapp.com/attachments/1145220489615261798/1183746865695571989/image_-_2023-12-11T070853.889.png?ex=6589752d&is=6577002d&hm=d9e7caaa586b70c396cf1087eaa807ac14965fec25e9264822bb21a7bc7053aa&

**Comment by gavinostler** [comment]
Under Review...

**Comment by gavinostler** [comment]
Currently on backlog. Feature accepted.

**Comment by gavinostler** [comment]
Pushed a release with a fix for this. 👍
