### ISSUE TITLE
Inventory while in creating a party.

### ISSUE THREAD

**Issue by CasualDjungelskogBelieverReal** [Nexyl-Roblox/Issues#19]
### Description

So, I was checking out the silly new UI for the thing (looks really cool), and then I started a party. However, the new ui never went away. This would then allow me to press inventory and cause whatever the image displays.

I might've also caused another bug in where you can press inventory twice and you can basically keep one.

### Reproduction steps

```bash
Lobby
Create party
Side UI
Press inventory
Press equip
boom.
I might've also caused another bug in where you can
```

### Screenshots

```bash
https://cdn.discordapp.com/attachments/796583083431952384/1187402628506861579/image.png?ex=6596c1df&is=65844cdf&hm=1114a68e68d2287fcc8d8d77025cdf03649e92408b9a883dcd76bc296892f5e4&
```

### Logs

```bash
https://cdn.discordapp.com/attachments/796583083431952384/1187402947869552742/image.png?ex=6596c22b&is=65844d2b&hm=baf90f0b5a70db05d68168f8260290e752097da77ec9991385d0e4b8cddb1700&
```

### Experience

World

### OS

Windows

**Comment by gavinostler** [comment]
Closed, fixed as of 429bb07
