### ISSUE TITLE
VISUAL 22 -> 23 during wave 22

### ISSUE THREAD

**Issue by CasualDjungelskogBelieverReal** [Nexyl-Roblox/Issues#22]
### Description

In short, when you play up to wave 22 and pay attention to the wave above, when almost all enemies are dead, it switches to wave 23 (has no enemies) with the timer kept like normal.

### Reproduction steps

```bash
play up to wave 22
pay attention to the wave counter.
```

### Screenshots

```bash
I would need to have a video example to show.
```

### Logs

```bash
No errors are shown.
```

### Experience

Game

### OS

Windows

**Comment by gavinostler** [comment]
Game is missing an ending. intentional
