### ISSUE TITLE
Dashed Range line does not update quick enough.

### ISSUE THREAD

**Issue by CasualDjungelskogBelieverReal** [Nexyl-Roblox/Issues#27]
### Description

So I was just playing pd and the range circle became a literal math problem since it's just a line. However, the blue circle stays there. it points to where it's firing.

### Reproduction steps

```bash
legit just play the game wth and maybe have bad wifi or something funny
```

### Screenshots

```bash
https://media.discordapp.net/attachments/796583083431952384/1203313768445116416/image.png?ex=65d0a446&is=65be2f46&hm=c400ab0960a683a03c64af1e5da9df9eb4c2a4e951ab47becb9dbe222aae7555&=&format=webp&quality=lossless&width=1230&height=582
```

### Logs

```bash
no errors
```

### Experience

Game

### OS

Windows

**Comment by CasualDjungelskogBelieverReal** [comment]
If you don't like that it was written badly, I'll rewrite it.

**Comment by gavinostler** [comment]
BAHAHAHAH wait this is so funny... on my list of to-dos now.
