### ISSUE TITLE
the price for an upgrade is displayed on the incorrect layer.

### ISSUE THREAD

**Issue by swim38o** [Nexyl-Roblox/Issues#28]
### Description

the price is hidden under the tower display when you hover over the upgrade button

### Reproduction steps

```bash
1. go into a match
2. hover over the upgrade button
4. See error
```

### Screenshots

```bash
https://discord.com/channels/860721110487662614/1141619200448806922/1203362301462183987
```

### Experience

Game

### OS

Windows

**Comment by gavinostler** [comment]
Fixed as of Alpha 1.0.5 (Patch 1)
