### ISSUE TITLE
[BUGS] Banner Bugs

### ISSUE THREAD

**Issue by 0clut** [Nexyl-Roblox/Issues#30]
### Description

2/12/24 6:00 AM - 7:00 AM
(I use summon and pull interchangeably, sorry)
 
1: You can get a skin for a tower you do not own

2: Banner music plays over lobby music when you first join the game

3: You're able to click through the wish result UI, allowing you to speed up the summoning process. 

Notes:
You do not actually receive skins, though this is likely due to how early the feature is in development.

### Screenshots

```bash
(It's actually videos)
10x summon not working
https://cdn.discordapp.com/attachments/817215484768026635/1206580258820722688/10xSummonDoesntWork.mp4?ex=65dc866e&is=65ca116e&hm=e0456a07ba8151c603a6ecce38b0a9925d07b63da0e65becd72edc5bf78d5785&

12x summon + clickthrough bug (2.5x speed up)
https://cdn.discordapp.com/attachments/817215484768026635/1206580357344788512/12xSummon_and_Clickthru.mp4?ex=65dc8686&is=65ca1186&hm=3fd6a6414cd6a5012a64994c542b870d68999c67ada72907f45d94aeef062e11&

Music Overlapping 
https://cdn.discordapp.com/attachments/817215484768026635/1206581652818763826/Music_Overlap.mp4?ex=65dc87bb&is=65ca12bb&hm=839d61b31a725ae2abab5a7754c9759e3eab742559fa2bc460899fb68341fe92&
```

### Experience

Lobby

### OS

Windows

**Comment by gavinostler** [comment]
Fixed as of 2/12/24 at 9:25 PM
