### ISSUE TITLE
[BUG] - Banner music plays instead of lobby music

### ISSUE THREAD

**Issue by 0clut** [Nexyl-Roblox/Issues#31]
### Description

When you first join a lobby, the banner music plays instead of the lobby music. It's similar to the overlapping music bug, but this time the lobby music just doesn't play

When you open and close the banner menu, the lobby music comes back and the banner menu is silenced again. 

(forgot to look at logs, it's been a second since I've bug reported for anything)

### Reproduction steps

```bash
Join a game with your volume at an audible level
```

### Screenshots

```bash
https://cdn.discordapp.com/attachments/817215484768026635/1215784572113916075/Roblox_2024-03-08_17-09-21.mp4?ex=65fe029e&is=65eb8d9e&hm=78695931388f4f09e1d162eb75968d4b3cbaf1d6801ad85453c6debe182c0d8c&
```

### OS

Windows

**Comment by gavinostler** [comment]
fixed as of Alpha 1.0.3 (Patch 1)
