### ISSUE TITLE
[BUG] - Alpha 1.0.5 (Patch 1) General testing

### ISSUE THREAD

**Issue by 0clut** [Nexyl-Roblox/Issues#33]
### Description

**Shit I found when testing banners**
When you enter the banner menu, the banner music doesn't play until you complete a summon
And when you DO complete a summon (and back out of the banner menu) the lobby music is absent.
Opening the banner menu again resumes the lobby music as normal. Though doing a summon again will repeat the process.
(the lobby music also plays during the summon animation)

### Reproduction steps

```bash
Uh... I should pay more attention to this part huh?

Just do a summon with your volume up
```

### Screenshots

```bash
https://cdn.discordapp.com/attachments/817215484768026635/1229890387632455871/PDTesting1.mp4?ex=663153ae&is=661edeae&hm=481f22fb96c44dd2aef1852f59a39914927ddbb98e0142ecbe83779afe8cdd37&
```

### Logs

```bash
Uh hi :3
```

**Comment by gavinostler** [comment]
screw banners for now :3
