### ISSUE TITLE
[BUG] - 6/18/24 General Testing

### ISSUE THREAD

**Issue by 0clut** [Nexyl-Roblox/Issues#35]
### Description

Banner menu music doesn't play until you complete a summon. Closing the banner menu mutes all music, and re-opening continues the original PolyDefense lobby theme. (Music glitches bring us together Java)

The "spawnClient" and "spawn" command(s) spawns one more than you asked for. (1000 turns into 1001)

Surprisingly, that's it. Good job your game works :3

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
:3
```

### Experience

Game

### OS

Windows

**Comment by gavinostler** [comment]
fixed
