### ISSUE TITLE
[BUG] - <Tower Rings>

### ISSUE THREAD

**Issue by 0clut** [Nexyl-Roblox/Issues#36]
### Description

Tower rings are based on which tower was placed first, not proximity

If you deselect the tower you are about to place while tower rings are generating, the rest will remain visible until you select another tower

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
https://cdn.discordapp.com/attachments/817215484768026635/1254926922891133080/Sped.mp4?ex=667b4545&is=6679f3c5&hm=bdf6c5874b3b49ff0bf3c6d1fc2641bed8af718b3420cdba14695cdcf55489f7&
```

### Logs

```bash
:3
```

### Experience

Game

### OS

Windows

**Comment by gavinostler** [comment]
Should be fixed in
